[source]
type = "N2N"
address = "preprod-node.play.dev.cardano.org:3001"

#address = "relays-new.cardano-mainnet.iohk.io:3001"

[enrich]
type = "Sled"
db_path = "./sled_db"

#[[reducers]]
#type = "UtxoByNft"
#key_prefix = "AddressByBook"

[[reducers]]
type = "BookByAddress"
key_prefix = "BookHolder"
#policy_ids_hex = ["952a95a45c76664174e64a124704afaac2e69f640ab658a8a507cd23"]
convert_to_ascii = true

[[reducers]]
type = "AssetMetadata"
projection = "Json"
policy_asset_index = true
historical_metadata = true
#policy_ids_hex = ["952a95a45c76664174e64a124704afaac2e69f640ab658a8a507cd23"]

#[[reducers]]
#type = "AddressByAsset"
#key_prefix = "AddressByAsset"
#policy_id_hex = "952a95a45c76664174e64a124704afaac2e69f640ab658a8a507cd23"
#convert_to_ascii = false

[[reducers]]
type = "AddressesByStake"
key_prefix = "AddressByStake"

## Bible
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "test"
#policy_id_hex = "477cec772adb1466b301fb8161f505aa66ed1ee8d69d3e7984256a43"
#convert_to_ascii = true

## Alice in the wonderland
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "9cb921b32bfe214a739ed824f3f2da4e16c535a5448253d2951cc732"
#convert_to_ascii = true

## Art of war
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "59451c4d18a7992cebfee65a278cd1cdb35c4d3d2503c829466c710e"
#convert_to_ascii = true

## Peter Pan
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "5744fc711353f313cb919ee5e8738027a11062eaedb69a101b0f591a"
#convert_to_ascii = true

## Great Gatsby
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "80c613ceadc1aa49422925bfc962b2519a6ae1bf6e2f8ec749df5ed8"
#convert_to_ascii = true

## Wizard of Oz
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "caf75c38e02911d3291652e142f255194f344672f198ebeeaf1c0124"
#convert_to_ascii = true

## Doctor dolittle
#[[reducers]]
#type = "AssetHoldersByAsset"
#key_prefix = "AddressByBook"
#policy_id_hex = "1acfa94c919a585bfe64c77aa10d3dd76ad71da126032f17a353eac1"
#convert_to_ascii = true
[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

#PREPROD
[intersect]
type = "Point"
value = [
    14591432,
    "2f91ee547ef2ec0d68e48d164b74223575a727996b4ea00671fad0d0d55e3293",
]
#MAIN
#[intersect]
#type = "Point"
#value = [
    #107807812,
    #"a08809f6d3410c21b4ec315a630edb8c80e9c03fa0a3a6a5db7baa76307f6bef",
#]

#long ago
#[intersect]
#type = "Point"
#value = [
#23751352,
#"1b8328e7a51fcf2ebd2b203d2a6ef8b918e6366c92ba89c598256b570a5f0af0",
#]

[chain]
type = "PreProd"
#type = "Mainnet"

[policy]
missing_data = "Default"
